name: Run

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0 */30 * *' # 每30天运行一次
  push:
    branches:
      - main
jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 配置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          pip install DrissionPage==4.0.5.6

      - name: run 
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          WX_URL: ${{ secrets.WX_URL }}
        run: |
          python login_script.py